version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
        testing_net:
            ipv4_address: 172.28.1.2

  Web_App_1:
    image: httpd
    container_name: Web_App_1
    volumes:
      - ./http1/index.html:/usr/local/apache2/htdocs/index.html
    expose:
      - "80"
    depends_on:
      - nginx
    networks:
        testing_net:
            ipv4_address: 172.28.1.3

  Web_App_2:
    image: httpd
    container_name: Web_App_2
    volumes:
      - ./http2/index.html:/usr/local/apache2/htdocs/index.html
    expose:
      - "80"
    depends_on:
      - Web_App_1
    networks:
        testing_net:
            ipv4_address: 172.28.1.4

  Web_App_3: 
    image: flavio
    container_name: Web_App_3
    volumes:
      - ./http3/index.html:/var/www/html/index.html
    expose:
      - "80"
    networks:
        testing_net:
            ipv4_address: 172.28.1.5


networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
